---
name: Plumbum::ManyProvider#values=
parent_path: plumbum/many-provider
signature: values=(values)
slug: values=
constructor: false
data_path: plumbum/many-provider/i-values=
params:
- description: the updated values.
  name: values
  type:
  - name: Hash
    keys:
    - name: String
    - name: Symbol
    values:
    - name: Object
version: "*"
