---
name: Plumbum::Providers::Plural#values
parent_path: plumbum/providers/plural
signature: values
slug: values
constructor: false
data_path: plumbum/providers/plural/i-values
returns:
- description: the key-value pairs returned by the provider.
  type:
  - name: Hash
version: "*"
